# ── Reviewers ─────────────────────────────────────────────────────────────────

addReviewers: true
numberOfReviewers: 0
useReviewGroups: true
reviewGroups:
  Flooding-Client:
    - 송재욱
    - 김준혁
    - 문강현
    - 한국
    - 지유
    - 이효은
    - Kimmina

# ── Assignees ─────────────────────────────────────────────────────────────────
addAssignees: author
numberOfAssignees: 0
useAssigneeGroups: false
# ── 필터링 ────────────────────────────────────────────────────────────────────
filterLabels:
  include: []
  exclude: []
runOnDraft: true
