# ── Reviewers ─────────────────────────────────────────────────────────────────

addReviewers: true
numberOfReviewers: 0
useReviewGroups: true
reviewGroups:
  Flooding-Client:
    - "zaewc"
    - "Dino0204"
    - "g-hyxn"
    - "koreahghg"
    - "jyuuuuu0"
    - "hyooeunn"
    - "ma94275"

# ── Assignees ─────────────────────────────────────────────────────────────────
addAssignees: author
numberOfAssignees: 0
useAssigneeGroups: false
# ── 필터링 ────────────────────────────────────────────────────────────────────
filterLabels:
  include: []
  exclude: []
runOnDraft: true
