"📩 Type: Feature/Function":
  - head-branch:
      [
        "^feat/.+",
        "^feature/.+",
        "^change/.+",
        "^refactor/.+",
        "^chore/.+",
        "^ci/.+",
      ]

"🐞 Type: Bug/Function":
  - head-branch: ["^fix/.+", "^hotfix/.+", "^bugfix/.+"]

"📜 Type: Feature/Document":
  - head-branch: ["^docs/.+"]

"🪽 Type: Release":
  - all:
      base-branch: ["^main$"]
      head-branch: ["^develop$"]
  - head-branch: ["^release/.+"]
