import type { User } from "./user";

const MOCK_STUDENT_SEEDS: Omit<User, "isBanned">[] = [
  {
    id: 1,
    name: "박건우",
    studentNumber: 2501,
    grade: 2,
    classNumber: 5,
    number: 1,
    sex: "MAN",
    email: "s2501@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 101,
    dormitoryFloor: 1,
    specialty: "SW개발과",
    penaltyScore: 0,
  },
  {
    id: 2,
    name: "이수진",
    studentNumber: 2502,
    grade: 2,
    classNumber: 5,
    number: 2,
    sex: "WOMAN",
    email: "s2502@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 102,
    dormitoryFloor: 1,
    specialty: "SW개발과",
    penaltyScore: 0,
  },
  {
    id: 3,
    name: "김태양",
    studentNumber: 1301,
    grade: 1,
    classNumber: 3,
    number: 1,
    sex: "MAN",
    email: "s1301@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 103,
    dormitoryFloor: 1,
    specialty: "임베디드과",
    penaltyScore: 0,
  },
  {
    id: 4,
    name: "최아름",
    studentNumber: 1302,
    grade: 1,
    classNumber: 3,
    number: 2,
    sex: "WOMAN",
    email: "s1302@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 104,
    dormitoryFloor: 1,
    specialty: "임베디드과",
    penaltyScore: 0,
  },
  {
    id: 5,
    name: "정민호",
    studentNumber: 3401,
    grade: 3,
    classNumber: 4,
    number: 1,
    sex: "MAN",
    email: "s3401@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 105,
    dormitoryFloor: 1,
    specialty: "AI과",
    penaltyScore: 0,
  },
  {
    id: 6,
    name: "한지원",
    studentNumber: 2201,
    grade: 2,
    classNumber: 2,
    number: 1,
    sex: "WOMAN",
    email: "s2201@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 106,
    dormitoryFloor: 1,
    specialty: "정보보안과",
    penaltyScore: 0,
  },
  {
    id: 7,
    name: "오준혁",
    studentNumber: 1101,
    grade: 1,
    classNumber: 1,
    number: 1,
    sex: "MAN",
    email: "s1101@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 107,
    dormitoryFloor: 1,
    specialty: "SW개발과",
    penaltyScore: 0,
  },
  {
    id: 8,
    name: "윤서연",
    studentNumber: 2302,
    grade: 2,
    classNumber: 3,
    number: 2,
    sex: "WOMAN",
    email: "s2302@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 108,
    dormitoryFloor: 1,
    specialty: "임베디드과",
    penaltyScore: 0,
  },
  {
    id: 9,
    name: "강동현",
    studentNumber: 3201,
    grade: 3,
    classNumber: 2,
    number: 1,
    sex: "MAN",
    email: "s3201@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 109,
    dormitoryFloor: 1,
    specialty: "정보보안과",
    penaltyScore: 0,
  },
  {
    id: 10,
    name: "신예린",
    studentNumber: 1402,
    grade: 1,
    classNumber: 4,
    number: 2,
    sex: "WOMAN",
    email: "s1402@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 110,
    dormitoryFloor: 1,
    specialty: "AI과",
    penaltyScore: 0,
  },
  {
    id: 11,
    name: "임재원",
    studentNumber: 3301,
    grade: 3,
    classNumber: 3,
    number: 1,
    sex: "MAN",
    email: "s3301@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 111,
    dormitoryFloor: 1,
    specialty: "임베디드과",
    penaltyScore: 0,
  },
  {
    id: 12,
    name: "배수아",
    studentNumber: 2101,
    grade: 2,
    classNumber: 1,
    number: 1,
    sex: "WOMAN",
    email: "s2101@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 112,
    dormitoryFloor: 1,
    specialty: "SW개발과",
    penaltyScore: 0,
  },
  {
    id: 13,
    name: "조현준",
    studentNumber: 1201,
    grade: 1,
    classNumber: 2,
    number: 1,
    sex: "MAN",
    email: "s1201@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 113,
    dormitoryFloor: 1,
    specialty: "정보보안과",
    penaltyScore: 0,
  },
  {
    id: 14,
    name: "권나연",
    studentNumber: 3101,
    grade: 3,
    classNumber: 1,
    number: 1,
    sex: "WOMAN",
    email: "s3101@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 114,
    dormitoryFloor: 1,
    specialty: "SW개발과",
    penaltyScore: 0,
  },
  {
    id: 15,
    name: "문성민",
    studentNumber: 2401,
    grade: 2,
    classNumber: 4,
    number: 1,
    sex: "MAN",
    email: "s2401@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 115,
    dormitoryFloor: 1,
    specialty: "AI과",
    penaltyScore: 0,
  },
  {
    id: 16,
    name: "류하은",
    studentNumber: 1501,
    grade: 1,
    classNumber: 5,
    number: 1,
    sex: "WOMAN",
    email: "s1501@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 116,
    dormitoryFloor: 1,
    specialty: "AI과",
    penaltyScore: 0,
  },
  {
    id: 17,
    name: "서지훈",
    studentNumber: 3501,
    grade: 3,
    classNumber: 5,
    number: 1,
    sex: "MAN",
    email: "s3501@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 117,
    dormitoryFloor: 1,
    specialty: "AI과",
    penaltyScore: 0,
  },
  {
    id: 18,
    name: "남지우",
    studentNumber: 3402,
    grade: 3,
    classNumber: 4,
    number: 2,
    sex: "WOMAN",
    email: "s3402@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 118,
    dormitoryFloor: 1,
    specialty: "AI과",
    penaltyScore: 0,
  },
  {
    id: 19,
    name: "황도윤",
    studentNumber: 1102,
    grade: 1,
    classNumber: 1,
    number: 2,
    sex: "MAN",
    email: "s1102@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 201,
    dormitoryFloor: 2,
    specialty: "SW개발과",
    penaltyScore: 0,
  },
  {
    id: 20,
    name: "장소연",
    studentNumber: 2503,
    grade: 2,
    classNumber: 5,
    number: 3,
    sex: "WOMAN",
    email: "s2503@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 202,
    dormitoryFloor: 2,
    specialty: "SW개발과",
    penaltyScore: 0,
  },
  {
    id: 21,
    name: "전민준",
    studentNumber: 3102,
    grade: 3,
    classNumber: 1,
    number: 2,
    sex: "MAN",
    email: "s3102@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 203,
    dormitoryFloor: 2,
    specialty: "SW개발과",
    penaltyScore: 0,
  },
  {
    id: 22,
    name: "노지현",
    studentNumber: 1303,
    grade: 1,
    classNumber: 3,
    number: 3,
    sex: "WOMAN",
    email: "s1303@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 204,
    dormitoryFloor: 2,
    specialty: "임베디드과",
    penaltyScore: 0,
  },
  {
    id: 23,
    name: "심재원",
    studentNumber: 3502,
    grade: 3,
    classNumber: 5,
    number: 2,
    sex: "MAN",
    email: "s3502@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 205,
    dormitoryFloor: 2,
    specialty: "AI과",
    penaltyScore: 0,
  },
  {
    id: 24,
    name: "백다은",
    studentNumber: 2202,
    grade: 2,
    classNumber: 2,
    number: 2,
    sex: "WOMAN",
    email: "s2202@school.com",
    role: "GENERAL_STUDENT",
    dormitoryRoom: 206,
    dormitoryFloor: 2,
    specialty: "정보보안과",
    penaltyScore: 0,
  },
];

export const MOCK_STUDENTS: User[] = MOCK_STUDENT_SEEDS.map((student) => ({
  ...student,
  isBanned: false,
}));
