export const MOCK_MY_RESERVATION = {
  id: 0,
  tableName: "테이블 3",
  floor: "2F",
  members: ["2501 박건우"],
  periods: ["8교시", "9교시"],
  reason: "팀 프로젝트",
};

export const MOCK_RESERVATIONS = [
  {
    id: 1,
    tableName: "테이블 1",
    floor: "2F",
    members: ["2501 박건우", "2502 이수진"],
    periods: ["1교시", "2교시"],
    reason: "팀 프로젝트",
  },
  {
    id: 2,
    tableName: "테이블 2",
    floor: "3F",
    members: ["1301 김태양"],
    periods: ["3교시"],
    reason: "자습",
  },
  {
    id: 3,
    tableName: "테이블 3",
    floor: "4F",
    members: ["1302 최아름", "3401 정민호", "2201 한지원"],
    periods: ["2교시", "3교시", "4교시"],
    reason: "스터디",
  },
  {
    id: 4,
    tableName: "테이블 4",
    floor: "2F",
    members: ["1101 오준혁", "2302 윤서연", "3201 강동현", "1402 신예린"],
    periods: ["1교시"],
    reason: "조별 과제",
  },
  {
    id: 5,
    tableName: "테이블 5",
    floor: "3F",
    members: ["3301 임재원", "2101 배수아"],
    periods: ["4교시", "5교시"],
    reason: "시험 준비",
  },
  {
    id: 6,
    tableName: "테이블 6",
    floor: "4F",
    members: ["1201 조현준", "3101 권나연", "2401 문성민", "1501 류하은", "3501 서지훈"],
    periods: ["2교시"],
    reason: "프로젝트 발표 준비",
  },
  {
    id: 7,
    tableName: "테이블 1",
    floor: "2F",
    members: ["2501 박건우", "1301 김태양", "3201 강동현"],
    periods: ["11교시"],
    reason: "팀 프로젝트",
  },
];
