import { Music } from "./music";

export const MOCK_SONGS: Music[] = [
  {
    id: 1,
    title: "아이유 (IU) - 밤편지 (Through the Night) [Official MV]",
    studentNumber: 2501,
    studentName: "박건우",
    appliedAt: "08:30",
    thumbnailUrl: "",
  },
  {
    id: 2,
    title:
      "06. 멋진헛간 (Wonderful Barn) – 오대천왕 (The 5 Emperor) (정형돈, 밴드 혁오) (Jeong Hyeong Don, hyukoh)",
    studentNumber: 2502,
    studentName: "이수진",
    appliedAt: "14:14",
    thumbnailUrl: "",
  },
  {
    id: 3,
    title: "NewJeans (뉴진스) 'Hype Boy' Official MV (Performance ver.1)",
    studentNumber: 1301,
    studentName: "김태양",
    appliedAt: "09:22",
    thumbnailUrl: "",
  },
  {
    id: 4,
    title: "BTS (방탄소년단) 'Dynamite' Official MV",
    studentNumber: 1302,
    studentName: "최아름",
    appliedAt: "07:45",
    thumbnailUrl: "",
  },
  {
    id: 5,
    title: "IVE 아이브 'LOVE DIVE' MV",
    studentNumber: 3401,
    studentName: "정민호",
    appliedAt: "11:03",
    thumbnailUrl: "",
  },
  {
    id: 6,
    title: "BLACKPINK - 'Pink Venom' M/V",
    studentNumber: 2201,
    studentName: "한지원",
    appliedAt: "13:55",
    thumbnailUrl: "",
  },
  {
    id: 7,
    title: "aespa 에스파 'Girls' MV",
    studentNumber: 1101,
    studentName: "오준혁",
    appliedAt: "08:17",
    thumbnailUrl: "",
  },
  {
    id: 8,
    title: "SEVENTEEN (세븐틴) 'Super' Official MV",
    studentNumber: 2302,
    studentName: "윤서연",
    appliedAt: "10:40",
    thumbnailUrl: "",
  },
  {
    id: 9,
    title: "Stray Kids '소리꾼' M/V",
    studentNumber: 3201,
    studentName: "강동현",
    appliedAt: "12:00",
    thumbnailUrl: "",
  },
  {
    id: 10,
    title: 'TWICE "FANCY" M/V',
    studentNumber: 1402,
    studentName: "신예린",
    appliedAt: "15:30",
    thumbnailUrl: "",
  },
];
